version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./script-mysql.sql:/docker-entrypoint-initdb.d/script-mysql.sql
      - ./_volumes/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: mentoriadio
      MYSQL_ROOT_PASSWORD: aFQaG3FyFG5pjNZHeMy4mweSeJgruxjS92Gqv5U4p64EQ5vCLaDmQxXjx9HPbX5q
    cap_add:
    - SYS_NICE # CAP_SYS_NICE

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  _volumes: